# Citations with Pandoc and Zotero

Formatting and managing citations and bibliographies is often one of the more
annoying and tedious parts of writing a paper or report. Fortunately, you can
automate this process using RMarkdown. pandoc, the program that converts your
document from Markdown to other formats, has a built-in citation formatter.
This week, you will practice using Markdown to insert and format citations.

## Resources

- [The RStudio tutorial on RMarkdown citations](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)
- [Zotero](https://www.zotero.org/), a free and powerful citation management program
  - My professional hobby (I wrote and maintain the Zotero/CSL style for APA)
  - [Download the Zotero app and browser connector](https://zotero.org/download)
  - [Zotero Style Repository](https://zotero.org/)
  - [Zotero Quick Start guide](https://www.zotero.org/support/quick_start_guide)
- [The BetterBibTeX Zotero plugin](https://github.com/retorquere/zotero-better-bibtex/releases),
  how we connect RStudio to Zotero
- [The `rbbt` RStudio add-in](https://github.com/paleolimbot/rbbt)
  - Connect RStudio to Zotero
  - Search your Zotero library for citations
  - Format your citations and generate your bibliography file for you
- [The `citr` RStudio add-in](https://cran.r-project.org/web/packages/citr/index.html)
  - Connect RStudio to Zotero
    - Generate your bibliography file for you
    - Doesn't work well if you have a very large Zotero library
  - Search your Zotero library or a standalone bibliography file for citations
  - Format your citations for you
  

## Basics of Citing with Markdown

You add citations to your Markdown document by typing something like this:
`[@Wiernik2016IntraindividualPersonality]`. The `@` sign tells pandoc that you 
are inserting a citation. The `Wiernik2016IntraindividualPersonality` part is 
the "citation key"—an ID label used to indicate what reference you are citing. 
When pandoc formats this citation, it will look up this citation key in your
bibliography file (see below) for all of the item data (authors, title, year, 
etc.). pandoc will go through your whole document, formatting all of the 
citations according the the rules of your chosen citation style, then add the bibliography to the end. It's like magic.


## Your Bibliography File

To format your citations, you need to provide pandoc with a file that has your
bibliography in a structured, computer-readable format. The best format to use
is **CSL JSON** (.json).

This format looks like this:

```
[{
	"id": "Wiernik2016IntraindividualPersonality",
	"type": "article-journal",
	"author": [{
		"family": "Wiernik",
		"given": "Brenton M."
	}],
	"issued": {
		"date-parts": [
			[2016, 8, 1]
		]
	},
	"title": "Intraindividual personality profiles associated with Realistic interests",
	"container-title": "Journal of Career Assessment",
	"container-title-short": "J. Career Assess.",
	"volume": "24",
	"issue": "3",
	"page": "460-480",
	"DOI": "10.1177/1069072715599378",
	"language": "en"
}]
```

You can see that all of the information needed to make a reference is included
here (author, title, date, journal title, DOI, etc.). We will use a program 
to automatically generate this structure for us (see the 
[Zotero section below](#zotero)).

_Note:_ The name "CSL JSON" is two acronyms. CSL stands for "Citation Style 
Language"—the programming language the citation styles pandoc uses are written
in. JSON stands for "JavaScript Object Notation"—JSON is a standard  format used
by many computer programs to store data. They are lots of different types of JSON
formats; CSL JSON is specifically the format used to store bibliographic reference
information. CSL JSON is also sometimes called "citeproc JSON" or "JSON citeproc".

CSL JSON is the best format to use for storing bibliographic data for pandoc.
CSL JSON is pandoc's citation engine's native data format, so it can be imported
and processed without any data loss. You can use 
[other data formats](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html),
but you might lose some information or get incorrectly formatted citations if
you do. For example, the BibTeX/BibLaTeX (.bib) format is very popular, but is 
has major limitations if you need to cite anything other than a journal article, 
book, chapter, or website. I recommend you avoid it if possible. 

After you have compiled your bibliographic database, add it to the YAML header
in your RMarkdown file using the `bibliography` tag:

```
---
title: My Amazing Research Paper Title
author: Brenton M. Wiernik
output_format:
  html_document: 
    code_folding: hide
bibliography: references.json
```

When you knit the document, pandoc will look for the `references.json` file
in the folder where your .Rmd file is.


## Adding Citations to Your Document

To add a citation to a document, type them like this: `[@Wiernik2016]`. 
Citations go inside square brackets. For each citation, start with `@`, then
add the citation key from your bibliography file (see
[below](#zotero) for where to find the citation keys in Zotero). 

To cite multiple items in the same citation, separate the citekeys with a 
semicolon: 

`[@Wiernik2016; @Schmidt1977]`

To add page numbers, type `, p.` or `, pp.` after the citekey, then type the 
page number:

`[@Wiernik2016, p. 123-124]`

You can refer to other types of locators (e.g., chapter, section, paragraph, 
etc.) using the locator abbreviations listed [here])(https://zotero-odf-scan.github.io/zotero-odf-scan/).

You can also add prefixes or suffixes to your citation:

`[e.g., see @Wiernik2016, p. 125, for a great example]`

`[@Wiernik2016, pp. 123-124; but see @Freud1913 for counterexample]`

To write an in-text citation (outside of parentheses), omit the square brackets:

`@Wiernik2016 [p. 126]`

You can also suppress the author by typing `-` before `@`:

`Wiernik said, "This is an excellent study" [-@Wiernik2016, p. 123]`

To add a citation to your bibliography without citing it in text, add a 
`nocite:` field to your YAML metadata at the top of the document and enter
the citekeys there:

```
---
nocite: |
  @Hunter1988, @Ones1993
---
```


## Setting a Citation Style

pandoc formats references using Citation Style Language (.csl) styles.
You can find styles for thousands of different journals at the
[Zotero Style Repository](https://zotero.org/styles).

To specify the style for your document, add a `csl:` filed to your YAML
metadata and give the URL for the CSL style:

```
---
csl: https://www.zotero.org/styles/apa
---
```

You can find the URL for a style in the Zotero Style Repository by searching
for it, right-clicking on the style name in the search results, and selecting
"Copy Link".

I've written some additional versions of APA style (e.g., for meta-analyses)
that are available [here](https://github.com/bwiernik/zotero-tools). To use one
of these styles, click on the file name, then click the `Raw` button, then 
copy the URL for the page (e.g., [](https://raw.githubusercontent.com/bwiernik/zotero-tools/master/apa-meta-analysis.csl)).

(You can also give the path to a local `.csl` file saved on your computer, such
as in the same folder as your `.Rmd` file, but if you have an internet
connection, I usually find it easier to just point to the style online.)


## Zotero and BetterBibTeX

The easiest way to manage bibliography files and citekeys for writing is to use
the free and powerful program **Zotero**. Zotero is a reference management program.
You can use it to organize refernce information for items, organize PDFs and notes
for your research, share references with collaborators, and automatically format
references and citations in Word, Google Docs, LibreOffice, BibTeX, and Markdown.

(Zotero is also a personal hobby of mine. I wrote and maintain the Zotero CSL
style for APA style.)

### Installing Zotero

To install Zotero, download the installer from [here](https://zotero.org/download)
and run it. Also install the Zotero Connector for your web browser.

After installing Zotero, open up the [Zotero Preferences window](https://zotero.org/support/preferences)
to the "Cite" pane. Check the box for the "Include URLs for paper articles" option.

On the Zotero website, make a user account, then enter your account information
on the "Sync" pane of Zotero Preferences. This isn't strictly necessary, but it
is how you sync your items and files across computers and share items in Zotero
Groups.

### Saving Items to your Zotero Library

To add items to your library, the best method is to click the 
[Save to Zotero button](https://www.zotero.org/support/adding_items_to_zotero) 
in your web browser while on the publisher webpage. 

See [this page](https://www.zotero.org/support/adding_items_to_zotero) for other
options for adding items to your library.

**Important:** _Always_ double check the item data after importing. Some sites
provide low-quality data, and it's important to check and correct this right away.

A few notes on item data:
  - Always store authors' full names (not just initials) if possible. This will
    ensure proper disambiguation behavior in APA and other styles.
  - Always store item titles and book titles in sentence case (only first word
    and proper nouns capitalized; all other words in lowercase, including after
    a colon or dash). pandoc will make words uppercase as prescribed by the style
    rules.
  - Always be sure that the item has a DOI number. This is the single most-important
    part of a referecne, so be sure that
    - Install my [DOI Manager plugin](https://github.com/bwiernik/zotero-shortdoi/releases)
      to automatically retrieve a DOI for items on import if it is missing.
    - Right click on the plugin's `.xpi` file and choose Save Link As. Then,
      in Zotero, click Tools → Add-ons. Then, drag the `.xpi` file you downloaded
      onto the window that pops up.
      
See [here](https://www.zotero.org/support/kb/item_types_and_fields) for a description
of Zotero item types and fields.
      
### Installing and Setting Up BetterBibTeX

BetterBibTeX is a plugin for Zotero that expands its ability to work with Markdown
and LaTeX. 


After installing, open the [Zotero Preferences window](https://zotero.org/support/preferences)
to the BetterBibTeX pane. Here, you can set a few options. Some useful ones to
look at are:

On the Citation Keys tab:
  1. Citation key format
    - You can control what your citation keys look like. It's important for your
      keys to be unique, so don't do just `AuthorYear`. Instead, also include
      some words from the title. I use this format:
      - `[auth][year][veryshorttitle2_2]`
      - This looks like `Schaufeli2004JobDemands`
  2. QuickCopy format
    - Set this to "Pandoc"
  3. Surround Pandoc citations with brackets
    - Should pandoc citations be copied with or without brackets?

After installing BetterBibTeX, you can see the citation key for an item at the
top of the item information pane on the right side of the Zotero window. You
can click on this to select the key and copy it.

You can also manually set the citation key for an item by typing it like this
in the Extra field at the bottom of the item information pane:
  - `Citation key: Freud1913InterpretationDreams`

### Other Plugins

There are several other useful Zotero plugins you might want to use. See a
list of available plugins [here](https://zotero.org/support/plugins)

### Getting Help with Zotero

I am happy to answer Zotero questions. You can also ask questions on the
[Zotero forums](https://forums.zotero.org/) (I will probably be the one to
answer your questions there, too). You might also find the 
[Zotero documentation](https://zotero.org/support/) helpful.


## Inserting Citations with `rbbt`

You can manually copy the citekeys for your items from your Zotero library
to your Markdown document, but there are also two different RStudio plugins 
that can make this easier.

The first plugin is the `rbbt` R package. This package can connect RStudio with
BetterBibTeX, letting you use the same interface to insert citations into RMarkdown
as Zotero uses in Word and Google Docs.

First, install `rbbt` from GitHub:

```
remotes::install_github("paleolimbot/rbbt")
```

Then, in RStudio, click Tools → Addins → Browse Addins… Click Keyboard Shortcuts…
and search for Zotero. Add a shortcut for the Insert Zotero Citation command
(I use Alt + Z). Click Okay.

To insert a citation, first make sure Zotero is open. Then, type the shortcut 
you just set. The Zotero Add Citation window will pop up. You can search for an 
item by author, title, and/or year.

You can add page numbers, prefixes, or suffix from this popup window (see 
[here](https://www.zotero.org/support/word_processor_plugin_usage#customizing_cites) 
for details), or you can manually type them in your Markdown document
(but always add them from the popup window if you are writing in Word, LibreOffice,
or Google Docs).

When you are finishing writing and are ready to knit, add this line to your YAML
metadata: ``bibliography: "`r rbbt::bbt_write_bib("bibliography.json", overwrite = TRUE)`"`` 


## Inserting Citations with `citr`

The `citr` package is similar to `rbbt`, but it builds its own interface for
searching a .bib file or your Zotero libary. 

There are a couple of important limitations to `citr` that make me recommend `rbbt`
over it:

  1. It exports items as BibLaTeX instead of CSL JSON, so citations for items 
     that aren't journal articles, books, or chapters will often be wrong.
  2. It can have a hard time loading and running if your Zotero library is very
     large. 
     
If you do want to use `citr`, you can install it from CRAN:

```
install.packages('citr')
```

Then, in RStudio, click Tools → Addins → Browse Addins… Click Keyboard Shortcuts…
and search for Insert citation. Add a shortcut for the Insert citations command. 
Click Okay.

To insert a citation, first make sure Zotero is open. Then, type the shortcut 
you just set. Click the "Connect and Load Libraries" link at the bottom of the 
popup window. (If you are a member of many Group libraries, first click the 
Settings button at the bottom of the page and select only the libraries you
want to search; this can help to speed `citr` up.)

After your libraries are loaded, search for an item by author, title, and/or year.

`citr` will automatically build a `.bib` file with the references you cite as you
go. When you are done writing, remove unneeded references from your `.bib` file
by running the `tidy_bib_file()` function. 

Be sure to add `bibliography: references.bib` to your YAML metadata.


## Activities

- Import some journal journal articles or other items into your Zotero library
- Add citations to these items into an RMarkdown document
  - You can do this manually or using `rbbt` or `citr`
- Knit your Markdown document and see the formatted citations and bibliography
- When you write your final report for class, insert citations using Zotero
