
## Welcome to R

Now, we'll get you up to speed with a minimum "need to know" about using R and 
RStudio. We're going to assume you know nothing and start from the basics. We will
explore more of the R/RStudio landscape as the semester goes on.

The format of today's notes aim to teach R by exploration, so is essentially an 
activity guide with prompts for exploration. These are mostly all exercises 
we'll be doing together in class. 


## Why R?

Why R? Some points taken from [adv-r: intro](http://adv-r.had.co.nz/Introduction.html):

- Free, platform-wide
- Open source
- Comprehensive set of "add on" packages for analysis
- Huge community
- …

Alternatives exist for data analysis, python being another excellent tool, 
especially these days as more and more R-like functionality is added to it. The 
good thing about python is that it's faster and has better support for machine 
learning models. 



## Rmd Presentations

You can also make presentation slides using Rmd. A great resource is Yihui's 
[Rmd book, "Presentations" section](https://bookdown.org/yihui/rmarkdown/presentations.html).

Some types of formats:

- ioslides
- [xaringan](https://slides.yihui.name/xaringan/#1)
- [slidy](https://www.w3.org/Talks/Tools/Slidy2/#(1))
- [reveal.js](https://revealjs.com/#/)
- ...


### Activity: Exploring ioslides

Let's turn the file we've been working on into slides.

Together:

1. In RStudio, go to "File" -> "New File" -> "RMarkdown" -> 
   "Presentation" -> "ioslides". Explore!
2. Clear everything below the YAML header.
3. Copy and paste the tibble exploration we've been working on 
   (without the YAML header), and turn them into slides.
   
   
   
   
   
## Topic 3: Asking effective questions online (10 min)

(5 min)

We all get stuck sometimes. If you try taking [preliminary measures](https://wiernik-datasci.netlify.com/help-general/) such as googling, you may have to turn to writing a question on a discussion board. Making your question _effective_ is an art. 

To make your question effective, the idea is to make things as easy as possible for someone to answer. 

- Will they have to dig to find a resource you're talking about, or do you provide links?
- If your code isn't doing what you expect, or you don't know how to obtain an output, do you provide a [__reproducible example__](https://stackoverflow.com/help/minimal-reproducible-example) (aka "reprex")?
  - Ideally, someone should be able to copy and paste a chunk of code to reproduce the problem you are talking about.
- Is your reproducible example _minimal_, meaning you've removed all the unnecessary parts to reproduce the problem?

You'll probably find that the act of writing an effective question causes you to answer your own question!

### Asking questions - Activity (5 min)

__Commenting on some online questions__

1. My turn: Start an Issue on the [Announcements repo](https://github.com/USF-Pssych-DataSci-2020/Announcements/issues) called `Asking effective questions`.
2. Your turn: Find a question/issue or two that someone has posed online. Check out [Stack Overflow](https://stackoverflow.com/) for inspiration.
3. Your turn: Add a comment to the newly opened Issue with the following:
    - The URL to the thread/question
    - A few brief points on how the question is worded effectively or ineffectively. What would make it better, if anything?

We'll talk about some examples after you're done. 






### Merge conflicts (5 min)

If you change a file locally, and that same file (_and_ the same lines) get 
changed on the remote repo in a different way, you'll end up with a _merge conflict_.

You will need to resolve this conflict before you can continue working. Remember 
that your local copy is a second class citizen compared to the remote version, 
so you'll have to resolve things locally before pushing to the remote. 

### Merge conflicts: Activity (5 min)

Let's make a merge conflict, then fix it. 

1. Edit a line of your README both locally and remotely (on GitHub) to something 
   different in both cases. Commit both changes.
2. Try pulling your remote changes. You'll get a _merge conflict_. 
3. Update the file that has the conflict, commit your changes, and push.



### Undoing Changes (5 min)

There are many ways that work can be "undone" in git. We will only investigate 
three of the simpler methods. For more advanced methods, like reverting to a specific
previous commit in your repo history, check out these resources by 
[bitbucket](https://www.atlassian.com/git/tutorials/undoing-changes) and 
[GitHub](https://blog.github.com/2015-06-08-how-to-undo-almost-anything-with-git/). 


The three most useful "undo"s are:

1. Undoing your (uncommited) work and reverting to the previous commit.
2. Reverting a single previous commit.
3. Browsing the repo at previous states, and taking files from there. 

We'll demonstrate (1) and (2) in an activity.

### Undoing Changes: Activity (2 min)

Here's how to go back to the most recent commit:

1. First, make and save a change to (say) a README file in your participation repo.
2. In GitHub desktop, right-click on the file whose changes you want to discard.
   Click "Discard Changes". You can even select multiple files at once if you like.
   
Here's how to undo a specific previous commit:

1. In GitHub desktop, click on the History tab.
2. Right-click on the commit you want to revert and choose "Revert this commit".


### Getting weird errors? (3 min)

It's common to sometimes experience some errors in git, especially if you're first 
learning how to use it. Try to get yourself unstuck with the concepts we've discussed here first. 

But, you might find yourself stuck. The git documentation is full of jargon, 
making it difficult to read and therefore difficult to debug things. There's even 
a [parody](https://git-man-page-generator.lokaltog.net/) on it. If you are in 
this position, it's best to just [burn it all down](http://happygitwithr.com/burn.html). 
There's even an [xkcd comic](https://xkcd.com/1597/) on this.


### Tagging a Release (5 min)

Tagging a release on GitHub is like putting a "star" next to a particular commit. 
It highlights a particular point in time of your repository that is noteworthy, 
typically after achieving some milestone. This is easier to come back to than 
having to manually keep track of noteworthy points in your commit history.

Examples:

- At the end of teaching this class, I will tag a release so I can easily come back
  to earlier versions of the course in the future.
- After sufficient development of an R package like [psychmeta](https://github.com/psychmeta/psychmeta/releases), 
  a new release is tagged corresponding to the version of the package. 

### Tagging a Release: Activity (3 min)

Congratulations! We finished the first two weeks of DataSci and Programming, 
which focussed on _tools_. To mark this milestone, let's tag a release on our 
participation repositories.

1. On your GitHub repo online, click "Releases"
2. Click "Create a new release"
3. Fill in the fields:
    - It probably makes sense to use a versioning system like `week_2` here.
4. "Publish Release".


## Optional: Work with git in RStudio

It's possible to work with git/GitHub directly in RStudio, rather than using
GitHub Desktop. I usually work with GitHub Desktop, but do whatever works for you.
I can help you get RStudio working with git if you need a hand.

You might need to [configure your git](http://happygitwithr.com/hello-git.html) 
using the command line or the `usethis` package.

Your RStudio will probably be able to "find" git. But if it can't, you'll 
encounter errors. See [happygitwithr: see-git](http://happygitwithr.com/rstudio-see-git.html) 
for help. 

__Optional__ (but recommended): If you are on a laptop, after class, you might 
want to [cache](http://happygitwithr.com/credential-caching.html) 
your credentials so that you don't have to keep inserting your password.

### The typical workflow git in RStudio

Let's make a change to our repository from local.  

1. Cloning your participation repo.
    - In RStudio, File -> New Project -> Version Control -> Git.
    - You should see a `Git` tab in RStudio, upper-right corner window. 
      If not, see [happygitwithr: see-git](http://happygitwithr.com/rstudio-see-git.html) 
      for help.
    - Take a look at the files you just downloaded!
2. Make your README a little nicer. Maybe fix up the title.
3. Stage and commit the changes:
    - In the Git tab in RStudio, click the checkboxes for the files that you 
      want to commit. This is called "staging".
    - Click the "Commit" button.
    - Enter a commit message.
    - Click "commit". 
4. Push to your remote repository (which is named "origin")
    - Click the up arrow in the Git panel in RStudio.

<!-- 
# Leftover text.

3. Commit your changes. 

Notice that GitHub automatically displays markdown files nicely, but not HTML files.

Note: this exercise employs an effective _local_ git workflow, which we will 
address later on in class.

Together:

1. If you haven't already, clone your participation repository to your desktop.
2. In RStudio, open the file `navigating_github.md`.
    - Yes! RStudio also acts as a plain text editor!
3. Convert the `.md` file to both pdf and html by clicking the `Preview` or `Knit` button.
4. Commit the two new files and push them to GitHub.
-->