# Miscellaneous topics

## GitHub Pages

You can turn your GitHub repository into a website, by enabling __GitHub Pages__
on that repo. This is useful for something as small as being able to display 
HTML files without downloading a local copy of the repository, to something as 
big as making a full fledged website like the [course website](https://wiernik-datasci.netlify.com).

- If you make a GitHub repo called `yourusername.github.io`, and enable GitHub 
  Pages on that repo, then the URL of the website will be `https://yourusername.github.io/`.
- If you enable GitHub pages on any other repo, the URL for that repo will be
  `https://yourusername.github.io/name_of_other_repo`.
- Your homework repo's website URL will be: 
  `https://usf-psych-datasci-2020.github.io/DataSci-hw-<your-username>/`.

Learn more with GitHub's [GitHub Pages](https://pages.github.com/) tutorial.

### Practice with HTML file linking

We'll practice linking to an HTML file for today's exercise, by following the instructions on the (new!) ["Viewing and Linking to HTML Files"](https://wiernik-datasci.netlify.com/evaluation/assignments/#viewing-and-linking-to-html-files) on the assignments home page.
